### ISSUE TITLE
@Transactional은 무엇이며 왜 사용하는 것인가.

### ISSUE THREAD

**Issue by MatchaKim** [LIKELION-DKU-11th/BackendStudy#1]
## @Transactional에 대한 학습내용을 자유롭게 작성해주세요

**Comment by HiLeeS** [comment]
@Transactional은 스프링에서 지원해주는 선언적 트랜잭션 처리 어노테이션이다. 이를 메소드에 사용하면 코드 내에서 그 메소드를 호출할 때 메소드의 모든 작업들이 성공적으로 완료되어야 작업 묶음의 결과를 적용하거나, 작업 중 오류가 발생할 시에 이전의 작업들이 성공적이었더라도 없었던 일처럼 되돌려준다. 
이는 데이터베이스를 다룰 때 데이터 추가, 갱신, 삭제 등으로 이루어진 작업을 처리하던 중 오류가 발생할 시 모든 작업들을 원상태로 되돌릴 수 있다. 과제에서 사용되었던 조회수 증가 메소드 또한 게시글을 조회하는 과정에서 오류가 발생할 경우 조회수 증가가 처리되었을 때 없던 일로 할 수 있으며, 모든 작업들이 성공해야만 최종적으로 데이터베이스에 반영하도록 한다.

**Comment by JiSoo-Yang** [comment]
0. Transaction이란? 
데이터베이스의 상태를 변화시키기 위해서 수행하는 작업의 단위를 의미한다.
여기서 단위라는 말을 사용했는데, 쉽게 말하면 더 이상 쪼개질 수 없는 최소의 연산이라는 의미가 된다.

예를 들어, 만약 내가 쇼핑 앱을 켜서 상품을 구매하려고 한다.
그런데 결제를 하는 짧은 시간 사이에 아래와 같은 일이 벌어지면 어떨까?
- 해당 판매자가 상품의 가격을 바꿔버려서, 잘못된 금액이 결제됨
- 같은 상품을 다른 사람도 구매해서, 상품 재고는 1개인데 2명에게 결제됨
- 결제가 완료되기 직전에 네트워크가 끊겨서, 돈은 나갔지만 구매완료는 되지 않음

이러한 예외적 상황을 막기 위해서는 아래와 같은 조치가 필요하다.
- 내가 결제중일 때에는 판매자가 해당 상품의 정보를 바꿀 수 없게 함
- 내가 결제중일 때에는 해당 상품을 다른 사람이 결제하지 못하게 함
- 내 구매가 오류로 완료되지 않았다면, 결제된 금액을 환불처리 함
좀 더 간단하게 정리하면, 
"결제는 다른 사람과는 독립적으로 이루어지며, 과정 중에 다른 연산이 끼어들 수 없다. 오류가 생긴 경우 연산을 취소하고 원래대로 되돌린다. 성공할 경우 결과를 반영한다."

트랜잭션 역시, 위의 원칙을 바탕으로 한다. 그래서 어떠한 연산에 트랜잭션이 보장된다면, DB에서 의도치 않은 값이 저장되거나 조회되는 것을 막을 수 있다.

1. @Transactional 이란?
@Transactional은 클래스, 메소드, 인터페이스 위에 추가하여 사용하는 것으로, 해당 범위 내 메소드가 트랜잭션이 되도록 보장해준다. 다시 말해 메소드를 하나의 트랜잭션(단위)로 간주하여 해당 메소드가 종료되기 전까지 어떠한 개입이나 다른 변화가 반영되지 않는 것을 말한다. 이것을 '선언적 트랜잭션'이라고도 하는데, 직접 객체를 만들 필요 없이 선언만으로도 관리를 용이하게 해주기 때문이다.

2. @Transactional 사용 이유
Service에서 Mapper로 여러 SQL 쿼리를 처리할 때 그 중 하나가 오류가 난 경우 그 전에 실행되었던 SQL 쿼리들이 롤백이 되어야 데이터 베이스에 반영되지 않는다. 따라서 @Transactional 어노테이션을 사용하면, 비즈니스 로직에서 데이터베이스로 SQL 쿼리 처리 과정 중 java.lang.RuntimeException 에러가 발생했을 때 트랜잭션이 롤백이 되도록 만들어준다.

**Comment by kwjdgh1267** [comment]
@Transactional 어노테이션을 클래스에 작성시 내부의 모든 메서드에 적용.
메서드에 별도로 작성시 이것이 우선 적용.
이 어노테이션이 붙으면 중간에 문제가 생길경우 실행 이전 시점으로 돌아감.(원자성 보장)
테스트메서드에 작성시 정상적으로 완료되어도 원래상태로 롤백함.(테스트에 용이함)
이 어노테이션을 사용하면 비지니스 로직과 트랜잭션 처리를 구분할 수 있는 장점이 있음.(코드가 깔끔함)

**Comment by b0ran** [comment]
Transaction은 데이터베이스에서 사용되는 용어로 transaction은 데이터베이스 관리 시스템 또는 유사한 시스템에서 상태를 변화시키기 위해 수행하는 작업의 단위를 말한다.

스프링에서는 Transaction 처리를 지원하는데 @Transactional 어노테이션을 이용하여 사용할 수가 있다. 이를 선언적 트랜잭션이라고 부른다. @Transactional은 클래스, 메소드, 인터페이스 위에 추가하여 사용하는 것으로, 해당 범위 내 메소드가 트랜잭션이 되도록 보장해준다.

@Transactional이 추가되면, 트랜잭션 기능이 적용된 프록시 객체가 생성된다. 이 프록시 객체는 해당 어노테이션이 포함된 메소드가 호출될 경우, PlatformTransactionManager를 사용하여 트랜잭션을 시작하고, 정상 여부에 따라 Commit 또는 Rollback 한다. 쿼리에 문제가 생기면 자동으로 Rollback 시켜주기 때문에 편리하다는 장점이 있다. @Transactional를 사용하지 않았다면 직접 데이터를 복구해야한다는 번거로운 상황이 생긴다.

**Comment by 12hyeon** [comment]
Transaction
- 트랜잭션은 하나의 논리적 작업 단위로 수행되는 일련의 작업입니다.
-  원자성, 일관성, 격리성, 지속성을 보장하여 데이터의 정확성과 안전성을 유지하는 개념입니다.

@Transactional
- 메서드 또는 클래스에 적용하여 트랜잭션 설정에 사용합니다.
- Spring 컨테이너 외부 서비스에서 트랜잭션 지원을 사용하려는 사용자를 위한 것입니다.
- 트랜잭션 경계 내에서 성공적으로 수행되면 commit 되고,RuntimeException 이나 RuntimeException을 상속받는 예외가 발생하면 자동으로 rollback 됩니다.
